.TH "bumprace" "6" 
.SH "NAME" 
bumprace \(em a simple arcade game 
.SH "SYNOPSIS" 
.PP 
\fBbumprace\fR [\fB-f | \-\-fullscreen\fP]  [\fB-w | \-\-windowed\fP]  [\fB-s | \-\-nosound\fP]  [\fB-n | \-\-notfinal\fP]  [\fB-t | \-\-noparticles\fP]  [\fB-o | \-\-nofadeout\fP]  [\fB\-\-precision\fP]  [\fB-h | \-\-help\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBbumprace\fR command. 
.PP 
This manual page was written for the \fBDebian GNU/Linux\fP distribution 
because the original program does not have a manual page. 
Instead, it has documentation in /usr/share/doc/bumprace/README. 
.PP 
\fBbumprace\fR a simple arcade game. 
.SH "OPTIONS" 
.PP 
This program follows the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. 
.IP "\fB-f\fP           \fB\-\-fullscreen\fP         " 10 
Start in fullscreen mode (default). 
.IP "\fB-w\fP           \fB\-\-windowed\fP         " 10 
Start in windowed mode. 
.IP "\fB-s\fP           \fB\-\-nosound\fP         " 10 
Start without sound. 
.IP "\fB-n\fP           \fB\-\-notfinal\fP         " 10 
No title screen (nice for developers). 
.IP "\fB-t\fP           \fB\-\-noparticles\fP         " 10 
Turns off particles. Good for slow computers. 
.IP "\fB-o\fP           \fB\-\-nofadeout\fP         " 10 
No fadeout after crash (for slow computers). 
.IP "          \fB\-\-precision\fP         " 10 
Sets the precision of the collisions (default=10). 
.IP "\fB-h\fP           \fB\-\-help\fP         " 10 
Show summary of options. 
.SH "KEYS" 
.PP 
Player 1 
.IP "\fBarrow keys\fP         " 10 
moving 
.IP "\fBright control\fP         " 10 
special ability 
.PP 
Player 2 
.IP "\fBa\fP         " 10 
left 
.IP "\fBd\fP         " 10 
right 
.IP "\fBw\fP         " 10 
thrust 
.IP "\fBTAB\fP         " 10 
special ability 
.SH "AUTHOR" 
.PP 
This manual page was written by Christian T. Steigies <cts@debian.org> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU Free Documentation 
License, Version 1.1 or any later version published by the Free 
Software Foundation; with no Invariant Sections, no Front-Cover 
Texts and no Back-Cover Texts. 
.\" created by instant / docbook-to-man 
